#!/bin/bash
exec 3>&1 4>&2
trap 'exec 2>&4 1>&3' 0 1 2 3
exec 1>/var/log/dp-device-proxy/DeviceProxy-preinst-log.txt 2>&1
# Everything below will go to the output file:

# disable the watchdog - both network and serial
# the proxy will reenable it once it runs
watchDogDisabled=false
echo "start"
deviceId=$(grep -Po '"'"deviceId"'"\s*:\s*"\K([^"]*)' /etc/dp-device-proxy/setting.json)
echo $deviceId
deviceAddress=$(grep -Po '"'"deviceAddress"'"\s*:\s*"\K([^"]*)' /etc/dp-device-proxy/setting.json)
echo $deviceAddress
server=$(grep -Po '"'"server"'"\s*:\s*"\K([^"]*)' /var/lib/dp-device-proxy/server.json)
echo $server
rm -f /var/lib/dp-device-proxy/dp-device-proxy-version.txt
monodis --assembly /usr/lib/dp-device-proxy/DeviceProxy.dll >> /var/lib/dp-device-proxy/dp-device-proxy-version.txt
version=$(grep 'Version:' /var/lib/dp-device-proxy/dp-device-proxy-version.txt | awk '{print $2}' | sed 's/\.\([^.]*\)$/-\1/')
echo "Version          : $version"

endPoint='/proxy-status.json'
if [ "$server" = "LinuxStaging" ] ; then
  serverCommand="https://d2p-ems-staging.herokuapp.com$endPoint"
else
  serverCommand="https://www.dp-ems.com$endPoint"
fi


for serialPort in /dev/ttyUSB* 
do
  echo "$serialPort"
  chmod 777 $serialPort
  stty -F $serialPort 9600
  stty -F $serialPort cooked -echo
  exec 99<>$serialPort
  watchDogOffResponse="!:e0"
  response=""
  count=5

  while [ "$response" != "$watchDogOffResponse" ]; do
    printf "e0" >&99
    read -t 2 response <&99
    echo "$count:$response"
    let count=count-1
    if [ $count -lt 0 ]
    then
      break
    fi
  done

  exec 99>&-
  echo "port done"
  if [ $count -gt 0 ]
  then
    echo "watchdog disabled via serial"
    watchDogDisabled=true
    break
  fi
done
echo "all ports done"

generate_post_data()
{
  cat <<EOF
{
  "status": "false"
}
EOF
}

if [ "$watchDogDisabled" = false ]
then
  postCommand="$deviceAddress/setWatchDog"
  echo $postCommand
  statusCode=$(curl -i \
  -H "Accept: application/json" \
  -H "Content-Type:application/json" \
  -X POST --data "$(generate_post_data)" "$postCommand" --write-out %{http_code} --silent --output /dev/null)
  if [ "$statusCode" -ne "200" ]; then
    watchDogDisabled=true
    echo "watchdog disabled via network"
  fi
fi

if [ "$watchDogDisabled" = false ]
then
    echo "watchdog was not disabled"
fi

generate_update_start_post_data()
{
  cat <<EOF
{
  "mac": "$deviceId",
  "proxy_version": "$version",
  "status": "update-started"
}
EOF
}

echo "Server Ping parameters S:$server D:$deviceId V:$version "
echo $serverCommand
statusCode=$(curl -i \
-H "Accept: application/json" \
-H "Content-Type:application/json" \
-X POST --data "$(generate_update_start_post_data)" "$serverCommand" --write-out %{http_code} --silent --output /dev/null ) 

echo "ping update-started statusCode: $statusCode"

echo "stop dp-device-proxy.service if active"
STATUS="$(systemctl is-active dp-device-proxy.service)"
if [ "$STATUS" = "active" ]; then
    systemctl stop dp-device-proxy.service
fi
